### ISSUE TITLE
how to use YOLOv8x?

### ISSUE THREAD

**Issue by jihwan722** [matlab-deep-learning/Pretrained-YOLOv8-Network-For-Object-Detection#2]
Other versions of YOLOv8 do not produce errors when running runinference.m. However, when I run the YOLOv8x version, I encounter the following error. Is there a way to solve this?

--error--

Warning: Unable to load instances of class nnet.onnx.layer.VerifyBatchSizeLayer into a heterogeneous array.  The definition of
nnet.onnx.layer.VerifyBatchSizeLayer could be missing or contain an error.  Default objects will be substituted. 
> In runInference (line 13) 
Warning: While loading an object of class 'nnet.cnn.LayerGraph':
Array indices must be positive integers or logical values. 
> In runInference (line 13) 
Warning: While loading an object of class 'dlnetwork':
Error using dlnetwork
Dot indexing is not supported for variables of this type.

Error in dlnetwork.loadobj (line 992)
                    net = dlnetwork(in.LayerGraph, exampleInputs{:}, 'Initialize', in.Initialized);

Error in runInference (line 13)
data = load('yolov8x.mat'); 
> In runInference (line 13) 
Incorrect number or types of inputs or outputs for function getExternalLayers.

Error in dlnetwork/get.Layers (line 231)
            val = getExternalLayers(this.PrivateNetwork);

Error in detectYOLOv8 (line 20)
inputSize = dlnet.Layers(1).InputSize;

Error in runInference (line 18)
[bboxes, scores, labelIds] = detectYOLOv8(detector, I, numClasses, executionEnvironment);

**Comment by anandy22** [comment]
Hi @jihwan722 

I tried reproducing the error at my end. However, I was unable to do so.

Can you please help me with the following details:
a. Your current MATLAB version?
b. Your current Operating System?
c. Output of your ver command.

**Comment by jihwan722** [comment]
a. matlab 2023b update 7
b. win11
c. 
![image](https://github.com/matlab-deep-learning/Pretrained-YOLOv8-Network-For-Object-Detection/assets/127845632/bca65db2-854d-4da8-a287-bc4d3bc196bc)

Additionally, the same error occurs in an environment using the same MATLAB version with Ubuntu 20.04 operating system and in an environment with MATLAB version 2022b on Windows 10.

**Comment by viakkala** [comment]
@jihwan722  Can you install "[Deep Learning Toolbox Converter for ONNX Model Format](https://in.mathworks.com/matlabcentral/fileexchange/67296-deep-learning-toolbox-converter-for-onnx-model-format)" support package and try out the inference?

**Comment by jihwan722** [comment]
@viakkala Thank you. It's working well now!!!
