### ISSUE TITLE
How to use a YoloV8 model , fine tuned to dataset other than COCO dataset?

### ISSUE THREAD

**Issue by akshu2025** [matlab-deep-learning/Pretrained-YOLOv8-Network-For-Object-Detection#3]
Hi

I am using a YoloV8 model that i trained to detect potholes and trying to inference it in Matlab.
How can i convert my model to a matlab file?
Does the functions in the +helper folder support any YoloV8 model?
I would appreciate any support here!

Thanks

**Comment by viakkala** [comment]
You may use [importYOLOv8Model.m](https://github.com/matlab-deep-learning/Pretrained-YOLOv8-Network-For-Object-Detection/blob/main/importYOLOv8Model.m) function to import the pretrained onnx file into MATLAB format.
